#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 17 10:28:49 2019

@author: donsdev
"""
def rev(s):
    if s == ')':
        return '('
    else:
        return '['
        
while 1:
    inp = input()
    tok = 1
    if inp == '.':
        break
    stk = []
    sent = inp.replace(' ','')
    for l in sent:
        if l == '(' or l == '[':
            stk.append(l)
        elif l == ')' or l == ']':
            if stk and stk[-1] == rev(l):
                stk.pop()
            else:
                print('no')
                tok = 0
                stk.append(l)
                break
    if tok:
        if not stk:
            print('yes')
        else:
            print('no')
            